---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    gatewayAPI:
      enabled: true
      enableTLSRoutes: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: kubernetes
    k8sServiceHost: localhost
    k8sServicePort: 7445
    l2announcements:
      enabled: true
    loadBalancer:
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList: 10.244.0.0/16
      l2announcements:
        enabled: true
