apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubble.apps.lab.mxe11.nl`)
      kind: Rule
      services:
        - name: hubble-ui
          port: 80
  tls:
    secretName: hubble-ui-tls
