---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: traefik
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 300Mi

