---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../application.yaml
  - service.yaml

patches:
  - target:
      kind: Deployment
      name: traefik
    path: deployment-patch.yaml

configMapGenerator:
  - name: traefik-config
    behavior: merge
    files:
      - traefik-config.yaml
