---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
spec:
  source:
    helm:
      values: |
        deployment:
          replicas: 2  # Production override
        resources:
          limits:
            memory: "1Gi"
