---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-certificate.yaml
  - grafana-ingressroute.yaml
  - prometheus-certficate.yaml
  - prometheus-ingressroute.yaml
