---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-synology-csi-synology-iscsi-storage-provisioner
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.containeroo.ch
