---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
includes:
  talos:
    taskfile: .taskfiles/talos/Taskfile.yaml
    internal: false
tasks:
  deps:
    desc: Setup Python venv for scripts (if missing) and install deps
    cmds:
      - |
        if [ ! -d .venv ]; then python3 -m venv .venv; fi
      - . .venv/bin/activate && pip install --quiet pyyaml
  validate:apps:
    desc: Validate app.yaml metadata across apps/
    deps: [deps]
    cmds: [. .venv/bin/activate && python scripts/validate_app_metadata.py]
