---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-synology
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: democratic-csi-synology
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Driver config will be consumed as a YAML file
        driver-config-file.yaml: |
          driver: synology-iscsi
          instance_id: ""
          httpConnection:
            protocol: http
            host: {{ .host }}
            port: 5000
            username: {{ .username }}
            password: {{ .password }}
            allowInsecure: true
          synology:
            volume: {{ .volume }}
          iscsi:
            targetPortal: "{{ .host }}:3260"
            targetPortals: []
            interface: ""
            namePrefix: "csi-"
            nameSuffix: "-cluster1"
            targetGroups:
              - targetGroupID: 1
            extentCommentTemplate: "democratic-csi"
            lunTemplate: {{ .iqn | quote }}
            targetTemplate: {{ .iqn | quote }}
            chap:
              username: {{ .chap_username }}
              password: {{ .chap_password }}
              mutual_username: ""
              mutual_password: ""
            lunGroupAuthType: CHAP
            lungroupPrefix: "csi-"
            lunIdMin: 1
            lunIdMax: 255
  dataFrom:
    - extract:
        key: secret/democratic-csi/synology
