---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-client-config
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        client-info.yaml: |
          clients:
            - host: {{ .host }}
              port: {{ .port | default 5000 }}
              https: {{ .https | default "false" }}
              username: {{ .username }}
              password: {{ .password | quote }}
  dataFrom:
    - extract:
        key: secret/democratic-csi/synology
