---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-client-config
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
            - host: {{ .host }}
              port: 5000
              https: false
              username: {{ .username }}
              password: {{ .password }}
  dataFrom:
    - extract:
        key: secret/democratic-csi/synology
