apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.svc.local
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.11.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=false
