---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - apiservice.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/component: metrics-server
