---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  targetNamespace: synology-csi
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clientInfoSecret:
      name: client-info-secret
      create: false
    storageClasses:
      iscsi-delete:
        disabled: true
      iscsi-retain:
        disabled: true
      nfs-delete:
        disabled: true
      nfs-retain:
        disabled: true
      smb-delete:
        disabled: true
      smb-retain:
        disabled: true
      synology-iscsi-storage:
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          fsType: ext4
          dsm: 172.16.0.189
          location: /volume1
    volumeSnapshotClasses:
      delete:
        disabled: true
      retain:
        disabled: true
      synology-snapshotclass:
        deletionPolicy: Delete
