---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-gateway
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: '1'  # Deploy after Cilium CNI
spec:
  project: default
  source:
    repoURL: https://github.com/matjahs/omni-gitops
    targetRevision: HEAD
    path: apps/cilium-gateway/gateway/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
