---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble-ui
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://github.com/matjahs/omni-gitops.git
    targetRevision: HEAD
    path: apps/kube-system/hubble-ui/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
