---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  sources:
    - repoURL: https://helm.irsigler.cloud
      chart: uptime-kuma
      targetRevision: 2.22.0
      helm:
        valueFiles:
          - $values/apps/monitoring/uptime-kuma/overlays/production/values.yaml
    - repoURL: https://github.com/matjahs/omni-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
