apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls-cert
  issuerRef:
    name: cloudflare-dns-issuer
    kind: ClusterIssuer
  commonName: grafana.apps.lab.mxe11.nl
  dnsNames:
    - grafana.apps.lab.mxe11.nl
