apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  template:
    spec:
      containers:
      - name: argocd-notifications-controller
        command:
        - argocd-notifications
        - --app-label-selector=!testing
