apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  exec.enabled: 'true'
  application.resourceTrackingMethod: annotation
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  url: https://cd.apps.lab.mxe11.nl
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"

  # dex.config: |
  #   connectors:
  #     - type: github
  #       id: github
  #       name: GitHub
  #       config:
  #         clientID: $argocd-oidc-secret:clientID
  #         clientSecret: $argocd-oidc-secret:clientSecret
  #         orgs:
  #         - name: matjahs
