---
version: '3'
tasks:
  default:
    desc: Format and validate terraform files
    cmds: [terraform fmt -recursive, terraform validate]
    silent: true
  gen-secrets:
    desc: Generate secrets in vault from secrets.yaml
    cmds: [talosctl gen secrets --force > secrets.yaml]
