---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma-https
  namespace: monitoring
spec:
  parentRefs:
    - name: cilium-secure-gateway
      namespace: cilium-gateway-system
      sectionName: https
  hostnames: [uptime.apps.lab.mxe11.nl]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: uptime-kuma
    - backendRefs:
        - name: uptime-kuma
          port: 3001
