---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma-route
  namespace: monitoring
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-system
  hostnames: [uptime.apps.lab.mxe11.nl]
  rules:
    - backendRefs:
        - name: uptime-kuma
          port: 3001
