---
apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0
description: Prometheus, Grafana, and Alertmanager for Kubernetes monitoring
dependencies:
  - name: kube-prometheus-stack
    version: 68.2.2
    repository: https://prometheus-community.github.io/helm-charts
