---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
# Base resources for kube-prometheus-stack
# Helm chart deployed via ArgoCD multi-source (see applications/monitoring.yaml)
