---
# Kube-Prometheus-Stack Base Values
# Prometheus configuration
prometheus:
  enabled: true
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-csi-synology-csi-synology-iscsi-storage
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin  # pragma: allowlist secret
  persistence:
    enabled: true
    storageClassName: synology-csi-synology-csi-synology-iscsi-storage
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
# AlertManager configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-csi-synology-csi-synology-iscsi-storage
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
# Disable components not needed
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheusOperator:
  enabled: true
