---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "31.1.1"
    helm:
      values: |
        # EntryPoints are the network listeners for incoming traffic.
        ports:
          web:
            port: 80
            nodePort: 30000
            redirections:
              entryPoints:
                to: websecure
                scheme: https
                permanent: true

          websecure:
            port: 443
            nodePort: 30001

        api:
          dashboard: true
          insecure: false

        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.apps.lab.mxe11.nl`)
            entryPoints:
              - websecure
            middlewares:
              - name: dashboard-auth

        extraObjects:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: dashboard-auth-secret
            type: kubernetes.io/basic-auth
            stringData:
              username: admin
              password: changeme
          - apiVersion: traefik.io/v1alpha1
            kind: Middleware
            metadata:
              name: dashboard-auth
            spec:
              basicAuth:
                secret: dashboard-auth-secret

        ingressClass:
          enabled: true

        providers:
          kubernetsIngress:
            enabled: false
          kubernetesGateway:
            enabled: true

        gateway:
          listeners:
            web:
              port: 80
              protocol: HTTP
              namespacePolicy:
                from: ALL

            websecure:
              port: 443
              protocol: HTTPS
              namespacePolicy:
                from: ALL
              mode: Terminate
              certificateRefs:
                - kind: Secret
                  name: local-selfsinged-tls
                  group: ""

        logs:
          general:
            level: INFO
          access:
            enabled: true

        metrics:
          prometheus:
            enabled: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
