---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    omni-kube-service-exposer.sidero.dev/port: '50081'
    omni-kube-service-exposer.sidero.dev/label: Argo CD
    omni-kube-service-exposer.sidero.dev/icon: https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/argo-icon-color.png
