---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rfc2136-tsig-secret
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rfc2136-tsig-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: tsig-secret  # pragma: allowlist secret
      remoteRef:
        key: external-dns
        property: rfc2136-tsig-secret
