---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rfc2136-tsig-secret
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  # In Vault, the secret is stored at 'secret/data/external-dns' with the key 'rfc2136-tsig-secret'.
  target:
    name: rfc2136-tsig-secret
    creationPolicy: Owner
  data:
    - secretKey: tsig-secret
      remoteRef:
        key: external-dns
        property: rfc2136-tsig-secret
