---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: volume-test
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
        runAsUser: 65532
        runAsGroup: 65532
