apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
    # Static configuration
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    api:
      dashboard: true
      debug: false

    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true

    certificatesResolvers:
      letsencrypt:
        acme:
          email: your-email@example.com  # Update this
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web

    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true

    log:
      level: INFO

    accessLog: {}

    ping: {}
