---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: traefik
  app.kubernetes.io/component: ingress-controller

