---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <APP_NAME>
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <MANIFEST_URL>
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: <DEST_NAMESPACE>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
