---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argocd
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: argocd-values
      valuesKey: values.yaml
