---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-values
  namespace: external-dns
data:
  values.yaml: |-
    ---
    # RFC2136 provider for Technitium DNS
    fullnameOverride: external-dns
    sources: [service, ingress, gateway-httproute]
    provider:
      name: rfc2136
    domainFilters: [apps.lab.mxe11.nl]
    extraArgs:
      - --rfc2136-host=172.16.0.53
      - --rfc2136-port=53
      - --rfc2136-zone=lab.mxe11.nl
      - --rfc2136-min-ttl=60s
      - --rfc2136-tsig-keyname=externaldns-key
      - --rfc2136-tsig-secret-alg=hmac-sha256
      # - --rfc2136-tsig-axfr  # Enable if you want zone transfers
    env:
      # Override the Kubernetes service-injected value so the RFC2136 port flag sees a plain integer.
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: '53'
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: rfc2136-tsig-secret
            key: tsig-secret
    # Policy for record ownership
    policy: sync

    # Registry type for tracking ownership
    registry: txt
    txtOwnerId: external-dns
    txtPrefix: external-dns-

    # Sync interval
    interval: 1m

    # Log settings
    logLevel: info
    logFormat: text
