---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-csi-rbd-node-secret
  namespace: rook-ceph
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  # In Vault, the secret is stored at 'secret/data/rook-ceph' with the key 'ceph-csi-rbd-node-secret'.
  target:
    name: ceph-csi-rbd-node-secret
    creationPolicy: Owner
  data:
    - secretKey: user  # pragma: allowlist secret
      remoteRef:
        key: rook-ceph
        property: ceph-csi-rbd-node-secret
