---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-web-gateway
  namespace: cilium-gateway-system
  annotations:
    # Cilium L2-IPAM will automatically assign IP from cilium-gateway-pool
    # IP will be allocated from 172.16.20.208/28 range
    # external-dns.alpha.kubernetes.io/hostname: "*.apps.lab.mxe11.nl"
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All  # Allow HTTPRoutes from any namespace
