---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-gateway-pool
spec:
  blocks:
    - cidr: 172.16.20.208/28
    - start: 172.16.20.100
      stop: 172.16.20.103
  serviceSelector:
    matchExpressions:
      - key: io.cilium.gateway/owning-gateway
        operator: Exists  # Match any Gateway-owned service
