---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ip-pool.yaml
  - l2-announcement-policy.yaml
  - cilium-web-gateway.yaml
  - cilium-secure-gateway.yaml
  - reference-grant.yaml
